clc;
clear;
train_normal_mali=importdata('train_normal_mali_table.dat');
train_normal_mali_date=train_normal_mali.data;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%TF-RF%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
name=train_normal_mali.textdata(1,2:end);
sample=train_normal_mali.textdata(2:end,1);
IS_0_normal=train_normal_mali_date(1:332,:)~=0;
num_0_normal=sum(IS_0_normal,1);
IS_0_mali=train_normal_mali_date(333:end,:)~=0;
num_0_mali=sum(IS_0_mali,1);
rf_normal_mali=log2(1+num_0_normal.*(max(1,num_0_mali).^(-1)).*(74/332));
train_normal_mali_date=train_normal_mali_date.*rf_normal_mali;
train_normal_mali_date=array2table(train_normal_mali_date,'VariableNames',name,'RowNames',sample);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%rank sum test%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
B=varfun(@table_ranksum,train_normal_mali_date);
true_id=find(table2array(B)==1);
train_normal_behalf=train_normal_mali_date(1:332,true_id);
train_mali_behalf=train_normal_mali_date(333:end,true_id);
IDF_ranksum=rf_normal_mali(true_id);
writetable(train_mali_behalf,'train_mali.dat','WriteRowNames',true,'WriteVariableNames',true)
writetable(train_normal_behalf,'train_normal.dat','WriteRowNames',true)
str1=string(train_normal_behalf.Properties.VariableNames)';
str2=zeros(length(str1),1);
standard=table;
standard.ID=str1;
standard.train=str2;
test_mali_table1=importdata('test_mali_table.dat');
ID=string(test_mali_table1.textdata(2:end,1));
mali_test_join=table;
mali_test_join.ID=ID
mali_test_join(:,2:19)=num2cell(test_mali_table1.data);
mali_stand_test_outjoin=outerjoin(standard,mali_test_join,'MergeKeys',true)
mali_stand_test_join=join(standard,mali_stand_test_outjoin);
mali_stand_test_join.train=[];
tem_name=["ID",test_mali_table1.textdata(1,2:end)];
[x,y]=find(ismissing(mali_stand_test_join)==1);
mali_stand_test_join_tem=table2cell(mali_stand_test_join);
mali_stand_test_join_tem(sub2ind(size(mali_stand_test_join_tem),x,y))={0};
mali_stand_test_join_nona=cell2table(mali_stand_test_join_tem)
mali_stand_test_join_nona.Properties.VariableNames=tem_name;
name=table2array(mali_stand_test_join_nona(:,1));
sample=mali_stand_test_join_nona.Properties.VariableNames(2:end);
mali_stand_tem=table2array(mali_stand_test_join_nona(:,2:end));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%Calculated eigenvalue%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
mali_test_tem=test_mali_table1.data;
[x,y]=find(ismissing(mali_test_tem)==1);
mali_test_tem(sub2ind(size(mali_test_tem),x,y))=0;
sum_sample=sum(mali_test_tem,1);
mali_stand_new=mali_stand_tem./sum_sample;
mali_stand_test_join_end=mali_stand_new';
mali_stand_test_join_tf_idf=mali_stand_test_join_end.*IDF_ranksum;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%The eigenvalues are calculated%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
mali_stand_test_join_t=array2table(mali_stand_test_join_tf_idf,'VariableNames',name,'RowNames',sample);
writetable(mali_stand_test_join_t,'test_mali.dat','WriteRowNames',true)
test_normal_table1=importdata('test_normal_table.dat');
ID=string(test_normal_table1.textdata(2:end,1));
normal_test_join=table;
normal_test_join.ID=ID;
normal_test_join(:,2:84)=num2cell(test_normal_table1.data)
normal_stand_test_outjoin=outerjoin(standard,normal_test_join,'MergeKeys',true);
normal_stand_test_join=join(standard,normal_stand_test_outjoin);
normal_stand_test_join.train=[];
tem_name=["ID",test_normal_table1.textdata(1,2:end)];
[x,y]=find(ismissing(normal_stand_test_join)==1);
normal_stand_test_join_tem=table2cell(normal_stand_test_join);
normal_stand_test_join_tem(sub2ind(size(normal_stand_test_join_tem),x,y))={0};
normal_stand_test_join_nona=cell2table(normal_stand_test_join_tem);
normal_stand_test_join_nona.Properties.VariableNames=tem_name;
name=table2array(normal_stand_test_join_nona(:,1));
sample=normal_stand_test_join_nona.Properties.VariableNames(2:end);
normal_stand_tem=table2array(normal_stand_test_join_nona(:,2:end));
normal_test_tem=test_normal_table1.data;
[x,y]=find(ismissing(normal_test_tem)==1);
normal_test_tem(sub2ind(size(normal_test_tem),x,y))=0;
sum_sample=sum(normal_test_tem,1);
normal_stand_new=normal_stand_tem./sum_sample;
normal_stand_test_join_end=normal_stand_new';
normal_stand_test_join_tf_idf=normal_stand_test_join_end.*IDF_ranksum;
normal_stand_test_join_t=array2table(normal_stand_test_join_tf_idf,'VariableNames',name,'RowNames',sample);
writetable(normal_stand_test_join_t,'test_normal.dat','WriteRowNames',true)